UNEXPECTED_ERROR = "UNEXPECTED_ERROR"

INVALID_IMAGE_TYPE = "INVALID_IMAGE_TYPE"
INVALID_NUMBER_OF_FACE = "INVALID_NUMBER_OF_FACE"
IMAGE_EXISTS = "IMAGE_EXISTS"
INVALID_FILE_SIZE = "INVALID_FILE_SIZE"

FACESET_NOTFOUND = "FACESET_NOTFOUND"
FACESET_NAME_EXISTS = "FACESET_NAME_EXISTS"
INVALID_FACESET_NAME = "INVALID_FACESET_NAME"

FACE_TOKEN_EXISTS = "FACE_TOKEN_EXISTS"
FACE_TOKEN_NOTFOUND = "FACE_TOKEN_NOTFOUND"
BAD_QUALITY = "BAD_QUALITY"
INVALID_PERSON_ID = "INVALID_PERSON_ID"

SOURCE_URL_EXISTED = "SOURCE_URL_EXISTED"
INVALID_WEBSOCKET_SOURCE_URL = "INVALID_WEBSOCKET_SOURCE_URL"

CANNOT_READ_STREAM = "CANNOT_READ_STREAM"

INVALID_THRESHOLD_TIME = "INVALID_THRESHOLD_TIME"
INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
INVALID_SOURCE = "INVALID_SOURCE"
MISSING_ARGUMENTS = "MISSING_ARGUMENTS"



